BITS 16
ORG 0x7c00
MOV ECX,B
MOV ESI,T
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV AL, [ECX]
MOV AH,14
INT 16
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
DEC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
MOV AL, [ECX]
MOV AH,14
INT 16
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
DEC BYTE [ECX]
DEC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
DEC BYTE [ECX]
DEC BYTE [ECX]
DEC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
ADD BYTE [ECX],5
MOV AL, [ECX]
MOV AH,14
INT 16
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
MOV BYTE [ECX],0
ADD BYTE [ECX],50
ADD BYTE [ECX],50
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
ADD BYTE [ECX],5
ADD BYTE [ECX],5
INC BYTE [ECX]
INC BYTE [ECX]
INC BYTE [ECX]
MOV AL, [ECX]
MOV AH,14
INT 16
CLI
HLT
G:
MOV AL,[ESI]
ADD AL,65
times 510 - ($ - $$) db 0
dw 0xAA55
SECTION .bss
T RESB 50
B RESB 1000
